/* ======================================================================
   clientsApi.js — real backend calls for ClientsPage.jsx / ClientPortal.jsx
   / ClientIntakeForm.jsx.

   Matches AuthContext.jsx's own conventions exactly:
     - token read straight from localStorage["hopenix_auth_token"]
       (same TOKEN_KEY AuthContext already uses — no need to pass a
       token around, this reads it itself, same as AuthContext's own
       internal apiFetch does)
     - "Authorization: Token <key>" header (DRF TokenAuthentication)
     - base URL http://127.0.0.1:8000/api + app path

   STEP 2 of the staged rollout only wires up plain Client CRUD
   (dashboard.Client) — Projects/Modules/Invoices/ModuleRequests come in
   later steps once this is confirmed working.
====================================================================== */

// FIX (Add Client behaving "local-only" — Priority 1): this used to be a
// hardcoded "http://127.0.0.1:8000/api" literal with no way to point it
// anywhere else. clientPortalApi.js already solved this correctly — read
// VITE_API_BASE_URL, then ALWAYS normalize to end in exactly one "/api"
// regardless of whether the env var itself already includes it. (A first
// pass here only stripped a trailing slash, which broke as soon as
// VITE_API_BASE_URL was set WITHOUT "/api" on the end — every request in
// this file silently 404'd because the path builders below always assume
// API_BASE_URL already ends in "/api".) This now matches
// clientPortalApi.js's own hostBase normalization exactly.
import { API_BASE_URL } from "../apiConfig.js";
const TOKEN_KEY = "hopenix_auth_token";

async function apiFetch(path, options = {}) {
  const token = localStorage.getItem(TOKEN_KEY);
  const isFormData = options.body instanceof FormData;
  const headers = { ...(options.headers || {}) };
  if (!isFormData) headers["Content-Type"] = "application/json";
  if (token) headers["Authorization"] = `Token ${token}`;

  const res = await fetch(`${API_BASE_URL}${path}`, { ...options, headers });
  let data = null;
  try {
    data = await res.json();
  } catch {
    // some responses (e.g. 204 No Content on delete) have no body
  }
  if (!res.ok) {
    const message =
      (data && (data.detail || data.error || Object.values(data)[0])) || "Something went wrong. Please try again.";
    throw new Error(Array.isArray(message) ? message[0] : String(message));
  }
  return data;
}

/* ---------------------------------------------------------------------
   CLIENTS — dashboard.Client
--------------------------------------------------------------------- */

export function listClients(params = {}) {
  const qs = new URLSearchParams(params).toString();
  return apiFetch(`/dashboard/clients/${qs ? `?${qs}` : ""}`);
}

export function getClient(id) {
  return apiFetch(`/dashboard/clients/${id}/`);
}

export function createClient(data) {
  // FIX (client photo never reached the backend): the Add/Edit Client
  // form now sometimes needs to send a real file upload (the picked
  // avatar photo) alongside the rest of the fields — see
  // ClientsPage.jsx's buildClientPayload. A FormData body must be
  // passed straight through as-is; JSON.stringify()-ing it would just
  // serialize it to "[object FormData]".
  const isForm = data instanceof FormData;
  return apiFetch("/dashboard/clients/", { method: "POST", body: isForm ? data : JSON.stringify(data) });
}

export function updateClient(id, data) {
  const isForm = data instanceof FormData;
  return apiFetch(`/dashboard/clients/${id}/`, { method: "PATCH", body: isForm ? data : JSON.stringify(data) });
}

export function deleteClient(id) {
  return apiFetch(`/dashboard/clients/${id}/`, { method: "DELETE" });
}

export function generatePortalAccess(clientId) {
  return apiFetch(`/dashboard/clients/${clientId}/portal-access/`, { method: "POST" });
}

// Matches ClientPortal.jsx's LoginScreen — Client ID + email + the portal
// password generated by generatePortalAccess(). No auth header needed
// (AllowAny on the backend, which throttles + locks out repeated failures).
export function portalLogin(clientId, email, password) {
  return apiFetch(`/dashboard/clients/portal-login/`, {
    method: "POST",
    body: JSON.stringify({ id: clientId, email, password }),
  });
}

/* ---------------------------------------------------------------------
   PROJECTS + MODULES — projects.Project / projects.Module
   (wired up in Step 3)
--------------------------------------------------------------------- */

export function listClientProjects(clientId) {
  // Relies on ProjectViewSet actually honouring ?client= — see the
  // projects/views.py fix alongside this change; before that fix this
  // silently returned every project the logged-in user could see.
  return apiFetch(`/projects/?client=${clientId}`);
}
export function getProject(projectId) {
  return apiFetch(`/projects/${projectId}/`);
}
export function createProject(data) {
  return apiFetch("/projects/", { method: "POST", body: JSON.stringify(data) });
}
export function updateProject(projectId, data) {
  return apiFetch(`/projects/${projectId}/`, { method: "PATCH", body: JSON.stringify(data) });
}
// Soft-delete only (sets is_archived — see ProjectViewSet.destroy);
// admin-only on the backend.
export function deleteProject(projectId) {
  return apiFetch(`/projects/${projectId}/`, { method: "DELETE" });
}
export function createModule(projectId, data) {
  return apiFetch(`/projects/${projectId}/modules/`, { method: "POST", body: JSON.stringify(data) });
}
export function updateModule(projectId, moduleId, data) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/`, { method: "PATCH", body: JSON.stringify(data) });
}
export function deleteModule(projectId, moduleId) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/`, { method: "DELETE" });
}

/* ---------------------------------------------------------------------
   MODULE FILES — projects.ModuleFile. The real backend counterpart to
   ClientsPage.jsx's module "attachments" (screenshots/videos/zips ticked
   off against one module's checklist) — until now those only ever lived
   as base64 blobs in the client's localStorage row, never as a real
   uploaded file on disk. `file` must be an actual File/Blob, sent as
   multipart (same isForm pattern the rest of this module uses).
--------------------------------------------------------------------- */
export function listModuleFiles(projectId, moduleId) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/files/`);
}
export function uploadModuleFile(projectId, moduleId, file) {
  const form = new FormData();
  form.append("file", file);
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/files/`, { method: "POST", body: form });
}
export function deleteModuleFile(projectId, moduleId, fileId) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/files/${fileId}/`, { method: "DELETE" });
}

// FIX (Section 6/7/14 — Task Page upload must not be instantly visible on
// the Client Portal): staff's "Approved / Show on Portal" checkbox beside
// a submitted file. `approved` defaults true (checking the box); pass
// false to un-approve/hide it again. This is the ONLY thing that flips
// ModuleFile.approved in the backend, which is what
// dashboard/serializers.py's _module_attachments actually gates on for a
// client viewer — never rely on hiding it in the UI alone.
export function toggleModuleFileApproval(projectId, moduleId, fileId, approved = true) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/files/${fileId}/approve/`, {
    method: "POST",
    body: JSON.stringify({ approved }),
  });
}

// Same gate as toggleModuleFileApproval above, but for a module's
// live/staging LINK (Module.url). Before this, only uploaded files needed
// approval — a link pasted on the Task Page went straight to the Client
// Portal. Admin / project manager only on the backend; any later change to
// the link resets it to un-approved.
export function toggleModuleUrlApproval(projectId, moduleId, approved = true) {
  return apiFetch(`/projects/${projectId}/modules/${moduleId}/approve-url/`, {
    method: "POST",
    body: JSON.stringify({ approved }),
  });
}

/* ---------------------------------------------------------------------
   PROJECT DELIVERABLE ZIP — projects.Project.completed_zip
   FIX (Section 9/10 — Final Deliverable ZIP never reached the backend):
   ClientsPage.jsx's DeliverableZipSection used to only ever update local
   React state (setProjectDeliverableZip) with a base64 dataURL capped at
   5MB — there was no function anywhere in this file that actually POSTed
   the zip to the real /api/projects/<id>/zip/ endpoint the backend
   already exposes (see projects/views.py ProjectViewSet.upload_zip).
   Since the backend's `completed_zip` field was therefore always empty,
   the Client Portal — which reads deliverableZip from the BACKEND, not
   from this page's local state — could never show it either, no matter
   how large or small the file was.
--------------------------------------------------------------------- */
export function uploadProjectZip(projectId, file) {
  const form = new FormData();
  form.append("zip", file);
  return apiFetch(`/projects/${projectId}/zip/`, { method: "POST", body: form });
}
export function deleteProjectZip(projectId) {
  return apiFetch(`/projects/${projectId}/zip/`, { method: "DELETE" });
}

/* ---------------------------------------------------------------------
   ACTIVITY LOG — dashboard.ActivityLogEntry. Read-only: entries are
   written automatically by the backend itself at specific transitions
   (payment submitted/confirmed, module request accepted/declined,
   support request sent) — there's no direct-write endpoint, so there's
   no createActivity() here to match.
--------------------------------------------------------------------- */
export function listActivity(clientId) {
  return apiFetch(`/dashboard/activity/?client=${clientId}`);
}

/* ---------------------------------------------------------------------
   INVOICES — dashboard.Invoice (wired up in Step 4)
--------------------------------------------------------------------- */

// clientId is optional — omit it (or pass a falsy value) to fetch every
// invoice visible to the caller (every client, for staff). Used by
// ClientsPage.jsx's background poll that watches for client-submitted
// payment proofs across all clients at once instead of one at a time.
export function listInvoices(clientId) {
  return apiFetch(`/dashboard/invoices/${clientId ? `?client=${clientId}` : ""}`);
}
export function createInvoice(data) {
  return apiFetch("/dashboard/invoices/", { method: "POST", body: JSON.stringify(data) });
}
export function submitInvoicePayment(invoiceId, file) {
  const form = new FormData();
  form.append("payment_proof", file);
  return apiFetch(`/dashboard/invoices/${invoiceId}/submit-payment/`, { method: "POST", body: form });
}
export function confirmInvoice(invoiceId) {
  return apiFetch(`/dashboard/invoices/${invoiceId}/confirm/`, { method: "POST" });
}

// Admin's own "Record Payment" (bank transfer / cash / etc., logged
// manually — not a client-submitted screenshot). Unlike confirmInvoice
// above, this supports a PARTIAL amount: the backend invoice sits as
// "partial" until enough of these add up to cover it, then flips to
// "paid" on its own — see dashboard/views.py InvoiceViewSet.record_payment.
export function recordInvoicePayment(invoiceId, amount) {
  return apiFetch(`/dashboard/invoices/${invoiceId}/record-payment/`, {
    method: "POST",
    body: JSON.stringify({ amount }),
  });
}

/* ---------------------------------------------------------------------
   MODULE REQUESTS — dashboard.ModuleRequest (wired up in Step 4)
--------------------------------------------------------------------- */

export function listModuleRequests(params = {}) {
  const qs = new URLSearchParams(params).toString();
  return apiFetch(`/dashboard/module-requests/${qs ? `?${qs}` : ""}`);
}
export function createModuleRequest(clientId, moduleId) {
  return apiFetch("/dashboard/module-requests/", {
    method: "POST",
    body: JSON.stringify({ client: clientId, module: moduleId }),
  });
}
export function acceptModuleRequest(requestId) {
  return apiFetch(`/dashboard/module-requests/${requestId}/accept/`, { method: "POST" });
}
export function rejectModuleRequest(requestId) {
  return apiFetch(`/dashboard/module-requests/${requestId}/reject/`, { method: "POST" });
}

/* ---------------------------------------------------------------------
   INTAKE REQUESTS — dashboard.IntakeRequest (wired up in Step 7)
--------------------------------------------------------------------- */

export function submitIntakeRequest(data) {
  // ClientIntakeForm.jsx sends a FormData (it carries the payment
  // screenshot file). JSON.stringify(FormData) turns into "{}", which the
  // backend rejects — pass FormData straight through as-is.
  const isForm = data instanceof FormData;
  return apiFetch("/dashboard/intake-requests/", { method: "POST", body: isForm ? data : JSON.stringify(data) });
}
export function listIntakeRequests(status) {
  return apiFetch(`/dashboard/intake-requests/${status ? `?status=${status}` : ""}`);
}
export function approveIntakeRequest(requestId) {
  return apiFetch(`/dashboard/intake-requests/${requestId}/approve/`, { method: "POST" });
}
export function rejectIntakeRequestApi(requestId) {
  return apiFetch(`/dashboard/intake-requests/${requestId}/reject/`, { method: "POST" });
}

// Removes a pending intake request row outright — used after ClientsPage.jsx
// approves a request through its own (richer, admin-customizable) Add
// Client flow instead of the backend's own one-shot /approve/ action,
// which would otherwise create a second, differently-configured client.
// Best-effort cleanup only: the real client this request turned into has
// already been created and saved regardless of whether this succeeds.
export function deleteIntakeRequest(requestId) {
  return apiFetch(`/dashboard/intake-requests/${requestId}/`, { method: "DELETE" });
}

/* ---------------------------------------------------------------------
   DOCUMENTS — dashboard.Document
   Real file uploads persisted in Django media storage + Postgres.
   Staff uses these from ClientsPage.jsx's Documents tab; clients use
   the portal-auth equivalents in clientPortalApi.js.
--------------------------------------------------------------------- */

/** List all documents for a client. */
export function listDocuments(clientId) {
  return apiFetch(`/dashboard/documents/?client=${clientId}`);
}

/** Upload a new document for a client.
 *  `file`    — a File/Blob object (required)
 *  `clientId` — the dashboard.Client pk
 *  `projectId` — optional projects.Project pk to link the document to
 */
export function uploadDocument(clientId, file, projectId) {
  const form = new FormData();
  form.append("file", file);
  form.append("file_name", file.name);
  form.append("client", clientId);
  if (projectId) form.append("project", projectId);
  return apiFetch("/dashboard/documents/", { method: "POST", body: form });
}

/** Delete a document by id. Also deletes the file from disk on the backend. */
export function deleteDocument(documentId) {
  return apiFetch(`/dashboard/documents/${documentId}/`, { method: "DELETE" });
}

/* ---------------------------------------------------------------------
   TASK FILE ATTACHMENTS — tasks.ModuleFile mirror
   Sends a real file to the task's upload-file-attachment endpoint,
   which creates a ModuleFile row (cross-browser portal visibility) and
   appends a real HTTP URL entry to the task's attachments list.
--------------------------------------------------------------------- */

/**
 * Upload a non-ZIP file attachment for a task.
 * Creates a ModuleFile on the linked Module so the file appears in
 * ClientsPage and ClientPortal without needing localStorage.
 *
 * @param {number} taskId  — the backend Task pk
 * @param {File}   file    — the raw File to upload
 */
export function uploadTaskFileAttachment(taskId, file) {
  const form = new FormData();
  form.append("file", file);
  return apiFetch(`/tasks/tasks/${taskId}/upload-file-attachment/`, { method: "POST", body: form });
}